### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#51]
Do the regular stuff: check font sizes and that one can edit amenities using a text-to-speech interface.

- [x] All `IconButton`s should have tooltips.
- [x] The app should work fine with increased system font size.
- [ ] Check for screen readers: `RendererBinding.instance.setSemanticsEnabled(true)`.

https://docs.flutter.dev/development/accessibility-and-localization/accessibility

**Comment by Zverik** [comment]
Could not enable semantics and decided that screen readers are not the target, other than that it is done in 0.10.

**Comment by danieldegroot2** [comment]
_Sidenote: You can also check the accessibility of the Every Door website with ie. Google Lighthouse and [W3C validators](https://w3c.github.io/developers/tools/) (sorry, I'm just stating the obvious)._
